### ISSUE TITLE
Attempt to concatenate local 'env' (a nil value)

### ISSUE THREAD

**Issue by justusschock** [IllustratedMan-code/telescope-conda.nvim#2] opened 2022-05-03 17:42 UTC
Hey @IllustratedMan-code , Thanks for this extension, I really love it!

I have encountered one error though:

after picking an environment with `require'telescope'.extensions.conda.conda{}` the first time after starting up neovim, I get the following error:

```lua
E5108: Error executing lua ...cope-conda.nvim/lua/telescope/_extensions/conda/main.lua:80: attempt to concatenate local 'env' (a nil value)
stack traceback:
        ...cope-conda.nvim/lua/telescope/_extensions/conda/main.lua:80: in function 'env_to_bin'
        ...cope-conda.nvim/lua/telescope/_extensions/conda/main.lua:88: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:242: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
```

If I ignore that one and just hit enter, the activation works flawless, but it still is a bit annoying :)
Any Idea, where this might come from?

It definitely comes from [here](https://github.com/IllustratedMan-code/telescope-conda.nvim/blob/main/lua/telescope/_extensions/conda/main.lua#L80) with `env` being nil. 
Maybe the result from the telescope selection is not properly transferred?

It would be great to get this fixed. Otherwise it's a perfect extension!

Cheers

**Comment by IllustratedMan-code** [comment] 2022-05-04 17:37
I'm glad you like the extension! Try setting `vim.env.CONDA_DEFAULT_ENV` to `"base"` in your init file and see if the issue persists. This should be a simple fix if that works.

**Comment by justusschock** [comment] 2022-05-05 07:39
@IllustratedMan-code thanks, that indeed works. However, this feels strange together with the fact, that auto-enabling base should be prevented. In the meantime, I have found another fix for this and a few other problems I encountered at [my fork](https://github.com/justusschock/telescope-conda.nvim) which I would like to upstream if you want me to.

The fixes there include the following:
- Handle cases if `vim.env.CONDA_DEFAULT_ENV` is not set (`nil`) -> will default to base now.
- Handle cases, where Path does not yet contain the prefix (Happens if no env is pre-activated). Currently the substitution wouldn't work then (at least it didn't for me).
- Also rely on `vim.env.CONDA_PREFIX` if given (and the path corresponding to the selected env)
- Set other conda variables like `CONDA_PREFIX`, `CONDA_PYTHON_EXE` and `CONDA_PROMPT_MODIFIER`

As I said, I would be more then happy to upstream in case you want me to :)


A not really related question:
There isn't currently a way to persist the selected env, right? In VSCode for every project I need to select the interpreter only once, but here I need to set it every time I restart neovim.

**Comment by IllustratedMan-code** [comment] 2022-05-05 13:08
I'm happy to look at a pull request, so go right ahead! 
Unfortunately I don't know a good way to persist data over different sessions in neovim. The problem is that we need some way to save the setting to disk somewhere, and I don't think neovim has a good way of dealing with this yet.

I'll look into it though!

**Comment by justusschock** [comment] 2022-05-05 13:38
Thanks for looking into that. If there is anything I can help with, just let me know (although my lua knowledge is very limited).

I opened the PR in #3 :)

**Comment by IllustratedMan-code** [comment] 2022-05-05 13:54
This is my first ever lua project so any help is appreciated. I'll go ahead and make a standalone issue for the data persistence. I think there might be a way to do it with shada files, but it will take some digging. Thanks again! Closing now.

**Closed as completed by IllustratedMan-code** 2022-05-05 13:54 UTC
